USE [master]
GO

/****** Object:  Database [VehicleService]    Script Date: 2021/03/09 13:24:40 ******/
CREATE DATABASE [VehicleService]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VehicleService', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\VehicleService.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VehicleService_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER01\MSSQL\DATA\VehicleService_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VehicleService].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VehicleService] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VehicleService] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VehicleService] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VehicleService] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VehicleService] SET ARITHABORT OFF 
GO

ALTER DATABASE [VehicleService] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VehicleService] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VehicleService] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VehicleService] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VehicleService] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VehicleService] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VehicleService] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VehicleService] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VehicleService] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VehicleService] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VehicleService] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VehicleService] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VehicleService] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VehicleService] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VehicleService] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VehicleService] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VehicleService] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VehicleService] SET RECOVERY FULL 
GO

ALTER DATABASE [VehicleService] SET  MULTI_USER 
GO

ALTER DATABASE [VehicleService] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VehicleService] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VehicleService] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VehicleService] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VehicleService] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VehicleService] SET QUERY_STORE = OFF
GO

ALTER DATABASE [VehicleService] SET  READ_WRITE 
GO

